# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b24ab9335f0748bf3b53d0ae152ab1da"
name = "Verify COD Orders"
handle = "verify-cod-orders"
application_url = "https://intimate-integration-nobody-revised.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_themes"

[auth]
redirect_urls = [
  "https://intimate-integration-nobody-revised.trycloudflare.com/auth/callback",
  "https://intimate-integration-nobody-revised.trycloudflare.com/auth/shopify/callback",
  "https://intimate-integration-nobody-revised.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
